// Generated by the boxoffice_dashboard_data asset — do not edit by hand.
window.BOXOFFICE_DATA = {
  "season": {
    "label": "Summer season, July 1–8 2025",
    "first_show": "2025-07-01",
    "last_show": "2025-07-08",
    "last_order_date": "2025-07-07",
    "scans_through": "2025-07-07",
    "nights_scanned": 7
  },
  "goal": {
    "pct": 0.05,
    "target_net": 351924.3,
    "gap": 16758.29999999999
  },
  "totals": {
    "net": 335166.0,
    "gross": 360803.0,
    "tickets_sold": 7745,
    "tickets_kept": 7212,
    "refunded_tickets": 533,
    "refunded_rev": 25637.0,
    "refund_share_of_gross": 0.07105539588085465,
    "seats_total": 9600,
    "seat_sell_through": 0.8067708333333333,
    "net_per_kept_ticket": 46.473377703826955,
    "show_up_rate": 0.8389735364875701,
    "scanned": 5231,
    "marketing_spend": 9670.0,
    "attributed_net_clean": 153299.0,
    "rpd_blended": 15.853050672182006
  },
  "attribution": {
    "unattributed_dirty_net": 13703.0,
    "unattributed_dirty_orders": 150,
    "still_unattributed_net": 0.0,
    "organic_net": 181867.0,
    "organic_orders": 1937,
    "organic_tickets": 4172
  },
  "derived": {
    "best_event": {
      "name": "Neon Coyote",
      "net": 56314.0
    },
    "worst_event": {
      "name": "Glass Anthem",
      "net": 18742.0,
      "sold": 540,
      "sell_through": 0.45,
      "unsold_seats": 660
    },
    "best_worst_ratio": 3.004695336676982,
    "vip_sellout_nights": 6,
    "balcony_sellout_nights": 3,
    "tier_totals": {
      "GA": {
        "sold": 4902,
        "net": 173865.0
      },
      "Balcony": {
        "sold": 2090,
        "net": 102532.0
      },
      "VIP": {
        "sold": 753,
        "net": 58769.0
      }
    },
    "best_campaign": {
      "id": "CMP-02",
      "name": "VIP Love Letter",
      "channel": "email",
      "has_code": true,
      "spend": 120.0,
      "orders": 41,
      "tickets": 84,
      "net": 3513.0,
      "rpd": 29.275,
      "net_dirty": 843.0
    },
    "worst_tracked_campaign": {
      "id": "CMP-09",
      "name": "Last Call Push",
      "channel": "instagram",
      "has_code": true,
      "spend": 1100.0,
      "orders": 89,
      "tickets": 187,
      "net": 8079.0,
      "rpd": 7.344545454545455,
      "net_dirty": 7431.0
    },
    "untracked_campaign": {
      "id": "CMP-04",
      "name": "Retarget Blitz",
      "channel": "facebook",
      "has_code": false,
      "spend": 950.0,
      "orders": 0,
      "tickets": 0,
      "net": 0.0,
      "rpd": 0.0,
      "net_dirty": 0.0
    },
    "rpd_spread": 3.9859512315880674,
    "best_by_revenue_dirty": "Radio Week",
    "best_by_revenue_clean": "Summer Kickoff",
    "launch": {
      "day_net": 39430.0,
      "first4_net": 116798.0,
      "first4_share": 0.34847806758442085
    },
    "attendance": {
      "avg_rate": 0.8389735364875701,
      "no_shows": 1004,
      "best": {
        "name": "Laugh Track Live",
        "rate": 0.8974093264248705
      },
      "worst": {
        "name": "Static Bloom",
        "rate": 0.7142857142857143,
        "no_shows": 254,
        "delta_pts": 12.468782220185581
      }
    }
  },
  "events": [
    {
      "id": "EV-01",
      "name": "The Midnight Standard",
      "genre": "jazz",
      "date": "2025-07-01",
      "capacity": 1200,
      "sold": 984,
      "sell_through": 0.82,
      "gross": 44436.0,
      "net": 40900.0,
      "refunded_rev": 3536.0,
      "refunded_tickets": 78,
      "tiers": {
        "GA": {
          "sold": 627,
          "cap": 800,
          "net": 20808.0
        },
        "Balcony": {
          "sold": 257,
          "cap": 300,
          "net": 12272.0
        },
        "VIP": {
          "sold": 100,
          "cap": 100,
          "net": 7820.0
        }
      },
      "attendance": {
        "kept": 906,
        "scanned": 764,
        "show_up": 0.8432671081677704,
        "no_shows": 142
      }
    },
    {
      "id": "EV-02",
      "name": "Copper & Oak",
      "genre": "folk",
      "date": "2025-07-02",
      "capacity": 1200,
      "sold": 889,
      "sell_through": 0.7408333333333333,
      "gross": 36062.0,
      "net": 33113.0,
      "refunded_rev": 2949.0,
      "refunded_tickets": 70,
      "tiers": {
        "GA": {
          "sold": 544,
          "cap": 800,
          "net": 16192.0
        },
        "Balcony": {
          "sold": 249,
          "cap": 300,
          "net": 10396.0
        },
        "VIP": {
          "sold": 96,
          "cap": 100,
          "net": 6525.0
        }
      },
      "attendance": {
        "kept": 819,
        "scanned": 681,
        "show_up": 0.8315018315018315,
        "no_shows": 138
      }
    },
    {
      "id": "EV-03",
      "name": "Glass Anthem",
      "genre": "indie",
      "date": "2025-07-03",
      "capacity": 1200,
      "sold": 540,
      "sell_through": 0.45,
      "gross": 20524.0,
      "net": 18742.0,
      "refunded_rev": 1782.0,
      "refunded_tickets": 43,
      "tiers": {
        "GA": {
          "sold": 337,
          "cap": 800,
          "net": 9540.0
        },
        "Balcony": {
          "sold": 146,
          "cap": 300,
          "net": 5632.0
        },
        "VIP": {
          "sold": 57,
          "cap": 100,
          "net": 3570.0
        }
      },
      "attendance": {
        "kept": 497,
        "scanned": 416,
        "show_up": 0.8370221327967807,
        "no_shows": 81
      }
    },
    {
      "id": "EV-04",
      "name": "Brasswork Riot",
      "genre": "funk",
      "date": "2025-07-04",
      "capacity": 1200,
      "sold": 1117,
      "sell_through": 0.9308333333333333,
      "gross": 54480.0,
      "net": 50716.0,
      "refunded_rev": 3764.0,
      "refunded_tickets": 71,
      "tiers": {
        "GA": {
          "sold": 717,
          "cap": 800,
          "net": 26960.0
        },
        "Balcony": {
          "sold": 300,
          "cap": 300,
          "net": 16016.0
        },
        "VIP": {
          "sold": 100,
          "cap": 100,
          "net": 7740.0
        }
      },
      "attendance": {
        "kept": 1046,
        "scanned": 911,
        "show_up": 0.8709369024856597,
        "no_shows": 135
      }
    },
    {
      "id": "EV-05",
      "name": "Neon Coyote",
      "genre": "electronic",
      "date": "2025-07-05",
      "capacity": 1200,
      "sold": 1200,
      "sell_through": 1.0,
      "gross": 60500.0,
      "net": 56314.0,
      "refunded_rev": 4186.0,
      "refunded_tickets": 87,
      "tiers": {
        "GA": {
          "sold": 800,
          "cap": 800,
          "net": 30954.0
        },
        "Balcony": {
          "sold": 300,
          "cap": 300,
          "net": 16240.0
        },
        "VIP": {
          "sold": 100,
          "cap": 100,
          "net": 9120.0
        }
      },
      "attendance": {
        "kept": 1113,
        "scanned": 958,
        "show_up": 0.8607367475292004,
        "no_shows": 155
      }
    },
    {
      "id": "EV-06",
      "name": "Laugh Track Live",
      "genre": "comedy",
      "date": "2025-07-06",
      "capacity": 1200,
      "sold": 1021,
      "sell_through": 0.8508333333333333,
      "gross": 46310.0,
      "net": 43708.0,
      "refunded_rev": 2602.0,
      "refunded_tickets": 56,
      "tiers": {
        "GA": {
          "sold": 645,
          "cap": 800,
          "net": 23218.0
        },
        "Balcony": {
          "sold": 276,
          "cap": 300,
          "net": 13050.0
        },
        "VIP": {
          "sold": 100,
          "cap": 100,
          "net": 7440.0
        }
      },
      "attendance": {
        "kept": 965,
        "scanned": 866,
        "show_up": 0.8974093264248705,
        "no_shows": 99
      }
    },
    {
      "id": "EV-07",
      "name": "Static Bloom",
      "genre": "punk",
      "date": "2025-07-07",
      "capacity": 1200,
      "sold": 937,
      "sell_through": 0.7808333333333334,
      "gross": 39326.0,
      "net": 37412.0,
      "refunded_rev": 1914.0,
      "refunded_tickets": 48,
      "tiers": {
        "GA": {
          "sold": 575,
          "cap": 800,
          "net": 18428.0
        },
        "Balcony": {
          "sold": 262,
          "cap": 300,
          "net": 12000.0
        },
        "VIP": {
          "sold": 100,
          "cap": 100,
          "net": 6984.0
        }
      },
      "attendance": {
        "kept": 889,
        "scanned": 635,
        "show_up": 0.7142857142857143,
        "no_shows": 254
      }
    },
    {
      "id": "EV-08",
      "name": "Riverlight Orchestra",
      "genre": "classical",
      "date": "2025-07-08",
      "capacity": 1200,
      "sold": 1057,
      "sell_through": 0.8808333333333334,
      "gross": 59165.0,
      "net": 54261.0,
      "refunded_rev": 4904.0,
      "refunded_tickets": 80,
      "tiers": {
        "GA": {
          "sold": 657,
          "cap": 800,
          "net": 27765.0
        },
        "Balcony": {
          "sold": 300,
          "cap": 300,
          "net": 16926.0
        },
        "VIP": {
          "sold": 100,
          "cap": 100,
          "net": 9570.0
        }
      },
      "attendance": null
    }
  ],
  "daily": [
    {
      "date": "2025-06-20",
      "net": 39430.0,
      "tickets": 909
    },
    {
      "date": "2025-06-21",
      "net": 29161.0,
      "tickets": 690
    },
    {
      "date": "2025-06-22",
      "net": 24708.0,
      "tickets": 575
    },
    {
      "date": "2025-06-23",
      "net": 23499.0,
      "tickets": 555
    },
    {
      "date": "2025-06-24",
      "net": 16930.0,
      "tickets": 396
    },
    {
      "date": "2025-06-25",
      "net": 16434.0,
      "tickets": 378
    },
    {
      "date": "2025-06-26",
      "net": 15901.0,
      "tickets": 357
    },
    {
      "date": "2025-06-27",
      "net": 15779.0,
      "tickets": 378
    },
    {
      "date": "2025-06-28",
      "net": 15867.0,
      "tickets": 349
    },
    {
      "date": "2025-06-29",
      "net": 16313.0,
      "tickets": 388
    },
    {
      "date": "2025-06-30",
      "net": 20005.0,
      "tickets": 476
    },
    {
      "date": "2025-07-01",
      "net": 18718.0,
      "tickets": 447
    },
    {
      "date": "2025-07-02",
      "net": 17193.0,
      "tickets": 404
    },
    {
      "date": "2025-07-03",
      "net": 21329.0,
      "tickets": 474
    },
    {
      "date": "2025-07-04",
      "net": 18043.0,
      "tickets": 409
    },
    {
      "date": "2025-07-05",
      "net": 11951.0,
      "tickets": 259
    },
    {
      "date": "2025-07-06",
      "net": 8355.0,
      "tickets": 196
    },
    {
      "date": "2025-07-07",
      "net": 5550.0,
      "tickets": 105
    }
  ],
  "campaigns": [
    {
      "id": "CMP-02",
      "name": "VIP Love Letter",
      "channel": "email",
      "has_code": true,
      "spend": 120.0,
      "orders": 41,
      "tickets": 84,
      "net": 3513.0,
      "rpd": 29.275,
      "net_dirty": 843.0
    },
    {
      "id": "CMP-01",
      "name": "Summer Kickoff",
      "channel": "instagram",
      "has_code": true,
      "spend": 1800.0,
      "orders": 472,
      "tickets": 1007,
      "net": 43371.0,
      "rpd": 24.095,
      "net_dirty": 35130.0
    },
    {
      "id": "CMP-11",
      "name": "Encore Newsletter",
      "channel": "email",
      "has_code": true,
      "spend": 150.0,
      "orders": 36,
      "tickets": 77,
      "net": 3452.0,
      "rpd": 23.013333333333332,
      "net_dirty": 3272.0
    },
    {
      "id": "CMP-05",
      "name": "Search Brand",
      "channel": "google_search",
      "has_code": true,
      "spend": 700.0,
      "orders": 180,
      "tickets": 382,
      "net": 15656.0,
      "rpd": 22.365714285714287,
      "net_dirty": 15308.0
    },
    {
      "id": "CMP-10",
      "name": "Student Rush",
      "channel": "street_team",
      "has_code": true,
      "spend": 300.0,
      "orders": 78,
      "tickets": 157,
      "net": 6623.0,
      "rpd": 22.076666666666668,
      "net_dirty": 6623.0
    },
    {
      "id": "CMP-12",
      "name": "Partner Playlist",
      "channel": "youtube",
      "has_code": true,
      "spend": 500.0,
      "orders": 90,
      "tickets": 203,
      "net": 8809.0,
      "rpd": 17.618,
      "net_dirty": 8561.0
    },
    {
      "id": "CMP-03",
      "name": "Radio Week",
      "channel": "radio",
      "has_code": true,
      "spend": 2400.0,
      "orders": 454,
      "tickets": 972,
      "net": 42123.0,
      "rpd": 17.55125,
      "net_dirty": 41183.0
    },
    {
      "id": "CMP-07",
      "name": "Local Press Blast",
      "channel": "email",
      "has_code": true,
      "spend": 200.0,
      "orders": 41,
      "tickets": 78,
      "net": 3242.0,
      "rpd": 16.21,
      "net_dirty": 3242.0
    },
    {
      "id": "CMP-06",
      "name": "Street Team Flyers",
      "channel": "street_team",
      "has_code": true,
      "spend": 600.0,
      "orders": 91,
      "tickets": 191,
      "net": 8086.0,
      "rpd": 13.476666666666667,
      "net_dirty": 7918.0
    },
    {
      "id": "CMP-08",
      "name": "Genre Nights",
      "channel": "instagram",
      "has_code": true,
      "spend": 850.0,
      "orders": 109,
      "tickets": 235,
      "net": 10345.0,
      "rpd": 12.170588235294117,
      "net_dirty": 10085.0
    },
    {
      "id": "CMP-09",
      "name": "Last Call Push",
      "channel": "instagram",
      "has_code": true,
      "spend": 1100.0,
      "orders": 89,
      "tickets": 187,
      "net": 8079.0,
      "rpd": 7.344545454545455,
      "net_dirty": 7431.0
    },
    {
      "id": "CMP-04",
      "name": "Retarget Blitz",
      "channel": "facebook",
      "has_code": false,
      "spend": 950.0,
      "orders": 0,
      "tickets": 0,
      "net": 0.0,
      "rpd": 0.0,
      "net_dirty": 0.0
    }
  ],
  "levers": [
    {
      "key": "soft_night",
      "label": "Rescue the soft night",
      "amount": 8300,
      "detail": {
        "event": "Glass Anthem",
        "sell_through": 0.45,
        "target_sell_through": 0.65,
        "add_tickets": 240,
        "avg_net_per_ticket": 34.70740740740741,
        "unsold_seats": 660
      }
    },
    {
      "key": "vip",
      "label": "Reprice / expand VIP",
      "amount": 4900,
      "detail": {
        "sellout_nights": 6,
        "nights": 8,
        "vip_net_on_sellouts": 48674.0,
        "price_lift": 0.1
      }
    },
    {
      "key": "realloc",
      "label": "Reallocate ad spend",
      "amount": 7100,
      "detail": {
        "budget_moved": 2000.0,
        "source_rpd": 9.448205128205128,
        "target_rpd": 23.653094462540718,
        "incrementality": 0.25
      }
    },
    {
      "key": "refunds",
      "label": "Refunds → exchange credits",
      "amount": 3800,
      "detail": {
        "refunded_rev": 25637.0,
        "convert_rate": 0.15
      }
    }
  ],
  "levers_total": 24100
};
